version: '3.8'

services:
  yoru-pastebin:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_CONNECTION_STRING: ${DATABASE_CONNECTION_STRING}
      SERVER_PORT: ${SERVER_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yoru.rule=Host(`paste.alokranjan.me`)"
      - "traefik.http.routers.yoru.entrypoints=websecure"
      - "traefik.http.routers.yoru.tls=true"
      - "traefik.http.routers.yoru.tls.certresolver=default"
      - "traefik.http.routers.yoru.tls.domains[0].main=paste.alokranjan.me"
      - "traefik.http.services.yoru.loadbalancer.server.port=${SERVER_PORT}"
    networks:
      - web

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - web

  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certificates[0].certFile=/certs/cert.pem
      - --entrypoints.websecure.http.tls.certificates[0].keyFile=/certs/key.pem
      - --api.dashboard=true
      - --api.insecure=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  db_data:
