name: Deploy to VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Validate and add VM host
        run: |
          # Validate VM_HOST format
          if [[ -z "${{ secrets.VM_HOST }}" ]]; then
            echo "::error::VM_HOST secret is empty!"
            exit 1
          fi
          
          # Check for invalid characters
          if [[ "${{ secrets.VM_HOST }}" == *"*"* ]]; then
            echo "::error::VM_HOST contains invalid wildcard characters!"
            exit 1
          fi
          
          # Add to known_hosts with retries
          for i in {1..3}; do
            ssh-keyscan -H "${{ secrets.VM_HOST }}" >> ~/.ssh/known_hosts && break
            echo "Attempt $i failed. Retrying in 5 seconds..."
            sleep 5
          done
          
          # Verify host entry
          if ! grep -q "${{ secrets.VM_HOST }}" ~/.ssh/known_hosts; then
            echo "::error::Failed to add VM_HOST to known_hosts"
            exit 1
          fi

      - name: Deploy with debug
        run: |
          ssh -vvv -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd ${{ secrets.VM_PATH }}
            git pull origin main
            docker compose down
            docker compose up -d --build
          EOF
