name: Deploy to VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write PEM key to file
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > web-server.pem
          chmod 600 web-server.pem

      - name: Setup SSH directory and known_hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -i web-server.pem -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd ${{ secrets.VM_PATH }}
            git pull origin main
            docker compose down
            docker compose up -d --build
          EOF
